llm-d/llm-d-inference-sim

Makefile, README.md
- Adds the `REGISTRY` env var so users can push the image to registries other than `ghcr.io/llm-d`.
- Adds an `image-build-and-push` target to build and push the image.
=> Makefile: Adds image-build-and-push Target

.github/actions/docker-build-and-push/action.yml, Dockerfile
This PR changes the base image used to create a smaller docker image. In addition it will now build a multi-architecture image that is for Linux on both amd64 and arm64.
Fix: #40
=> feat: Create a minimal multi-architecture docker image

.github/actions/docker-build-and-push/action.yml
This PR adds an extra tag of latest to the build of the image of the simulator
fix: #46
=> feat: When creating a new image of the vLLM simulator always add a tag of latest

pkg/llm-d-inference-sim/simulator.go, pkg/llm-d-inference-sim/simulator_test.go
This PR adds the standard vLLM health and readiness HTTP endpoints to the simulator.
In particular it adds support for the `/health` and `/ready` HTTP endpoints. In both cases the simulator will always return an HTTP status code of 200 (OK) with a body of an empty JSON object ({}).
fix: #45
=> feat: Added standard vLLM health and readiness endpoints

pkg/llm-d-inference-sim/request.go, pkg/llm-d-inference-sim/response.go, pkg/llm-d-inference-sim/simulator.go, pkg/llm-d-inference-sim/streaming.go, pkg/llm-d-inference-sim/tools_utils.go, pkg/llm-d-inference-sim/utils.go
We now calculate usage data in one place for both text and chat completion, and pass it to the relevant functions.
This is the second part of #56 (fixes #56)
=> Calculate usage data once for both text and chat

Dockerfile, go.mod
Reduce the mirror image size **(118MB -> 36.8MB)** by using `gcr.io/distroless/static:nonroot`.
Before:
```
ghcr.io/llm-d/llm-d-inference-sim       latest          232d52460440   12 days ago      118MB
```
After:
```
ghcr.io/llm-d/llm-d-inference-sim      small-image         49ac536af322   5 seconds ago   36.8MB
```
=> feat: 🚀 Reduce the mirror image size

pkg/llm-d-inference-sim/simulator.go, pkg/llm-d-inference-sim/tools_test.go, pkg/llm-d-inference-sim/tools_utils.go, pkg/llm-d-inference-sim/utils.go
This is the missing part from #65 
Fixes #57
=> Support minItems and maxItems for array parameters in tools

README.md, pkg/llm-d-inference-sim/simulator.go
=> Fixed readme, removed error for --help

pkg/llm-d-inference-sim/streaming.go
Fixed a small crash when `stream_options` omitted from a streamed completion request.
Previously, if `stream_options` omitted:
```bash
curl -H 'Content-Type: application/json' \
-X POST http://localhost:8000/v1/chat/completions \
-d '{
"model": "Qwen/Qwen2.5-1.5B-Instruct",
"messages": [{"role": "user", "content": "Test"}],
"max_tokens": 50,
"stream": true
}'
"chat completion request received"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x1050b0124]
goroutine 7 [running]:
github.com/llm-d/llm-d-inference-sim/pkg/llm-d-inference-sim.(*VllmSimulator).sendStreamingResponse.func1(0x1400045e280)
/Users/jmadigan/Work/llm-d-inference-sim/pkg/llm-d-inference-sim/streaming.go:63 +0x184 …
```
=> fix: crash when omitted stream_options

pkg/common/common_suite_test.go, pkg/common/config.go, pkg/common/config_test.go, pkg/common/test_helpers.go, pkg/llm-d-inference-sim/simulator.go, pkg/llm-d-inference-sim/simulator_test.go
=> Code reorganization: moved configuration related code to common

.github/ISSUE_TEMPLATE/blank_issue.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/new-release.md
This PR adds new issue templates that are similar to those in llm-d-inference-scheduler in an attempt at conformity with llm-d.
fix: #113
=> feat: Add  new issue templates

Dockerfile, Makefile, README.md
In addition, fixes in readme file related to kv-cache feature
=> Use same version of tokenizer in both Dockerfile and Makefile

Makefile
This PR fixes two issues with the Makefile on MacOS. In particular:
1. It removes the need to add TARGETOS=linux when running make image-build
2. It removes the need to add TARGETARCH=X86_64 when running make download-tokenizer
=> fix: Makefile fixes for MacOS

pkg/llm-d-inference-sim/simulator.go, pkg/llm-d-inference-sim/simulator_test.go
Fixes: https://github.com/llm-d/llm-d-inference-sim/issues/158 
`server.Serve` was blocking indefinitely, updated to pass ctx into startServer.
=> Fix server interrupt

pkg/llm-d-inference-sim/simulator_test.go
Run test locally failed at https://github.com/llm-d/llm-d-inference-sim/blob/1cdd97ebeb6043be05caa7c20268766957d9dc16/pkg/llm-d-inference-sim/simulator_test.go#L781
But it is hard to reproduce.
=> Cast bounds type in tests to func def: latency, interToken, and timeToFirst (to int)

pkg/common/utils.go, pkg/common/utils_test.go
=> extend response length buckets calculation to have not necessary equally sized buckets

.gitignore, pkg/common/publisher_test.go, pkg/kv-cache/block_cache.go, pkg/kv-cache/kv_cache_sender.go, pkg/kv-cache/kv_cache_test.go
=> Use dynamic ports in zmq tests

Dockerfile
This PR makes the llm-d-inferece-sim image smaller by deleting the dnf cache created in the build.
This saves some 60MB in the size of the image.
Copied from a PR made to the llm-d-inference-scheduler.
=> chore: Make the image smaller

pkg/common/config.go, pkg/kv-cache/block_cache.go, pkg/kv-cache/kv_cache.go, pkg/kv-cache/kv_cache_test.go, pkg/llm-d-inference-sim/simulator.go, pkg/llm-d-inference-sim/simulator_test.go, pkg/llm-d-inference-sim/streaming.go, pkg/openai-server-api/request.go
Closes #178 
In addition, return error if tokenization fails.
Small code refactoring.
=> Take cached prompt tokens into account in prefill time calculation

pkg/common/utils.go, pkg/llm-d-inference-sim/simulator.go
This simplifies the use of `RandomNorm()`
=> Change RandomNorm from float types to int
